name: 'Test'

on: [push]

jobs:
  build:
    name: Test build of paperless-ngx
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Test build
      uses: home-assistant/builder@master
      with:
        args: |
          --test \
          --all \
          --target paperless-ngx \
          --docker-hub ${{ secrets.DOCKERHUB_USERNAME }} 
